screenshots_folder: "E:\\World of Warcraft\\_retail_\\Screenshots"
webhook_url: "https://discord.com/api/webhooks/1293685598858772570/fY14gdIeZxvu5zNGxr0icYPom7Rta1PH1g2S88fE-pa8NUnL8-2QWQS-xaiq79CFIM-6"